version: '3.8'

services:
  meshengine-builder:
    build: .
    volumes:
      - .:/workspace
      - ./output:/workspace/output
    working_dir: /workspace
    command: /bin/bash
    environment:
      - DISPLAY=${DISPLAY}
    stdin_open: true
    tty: true 